name: Sast 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  sast: 
    runs-on: ubuntu-latest 
    name: sast-scan 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: bandit-scan  
      run : |
            cd $GITHUB_WORKSPACE 
            pip install bandit
            bandit -r Tiredful-API >> output.txt || true 
    - uses: actions/upload-artifact@v3
      if: always()
      with:
         name: my-artifact
         path: output.txt # or path/to/artifact
    - name: semgrep-scan  
      run : |
            cd $GITHUB_WORKSPACE 
            ls
            pwd
            python3 -m pip install semgrep
            semgrep --config "p/nodejsscan" --json -o semgrep.json
    - uses: actions/upload-artifact@v3
      if: always()
      with:
         name: my-artifact
         path: semgrep.json # or path/to/artifact
