name: dast 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  dast-scanning: 
    runs-on: ubuntu-latest 
    name: dast scanning 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: SCAN the application 
      run : | 
             docker run -d --rm -p 8000:8000 --name tiredful  joshuawe45/certification:api
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
       target: 'http://localhost:8000/'
